// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "SUNET NOC",
            "url": "https://www.sunet.se/",
            "email": "noc@sunet.se"
        },
        "license": {
            "name": "BSD"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "register"
                ],
                "summary": "Register a JSON-LD URL with the index server",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/manifest.ManifestInfo"
                        }
                    }
                }
            }
        },
        "/search": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Search the index",
                "parameters": [
                    {
                        "type": "string",
                        "description": "query string",
                        "name": "query",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "list"
                        }
                    }
                }
            }
        },
        "/status": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "status"
                ],
                "summary": "Display status and version information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.StatusResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.StatusResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "mix"
                },
                "size": {
                    "type": "integer",
                    "example": 100
                },
                "version": {
                    "type": "string",
                    "example": "1.0"
                }
            }
        },
        "manifest.ManifestInfo": {
            "type": "object",
            "properties": {
                "@id": {
                    "type": "string"
                },
                "mm:creator": {
                    "type": "string"
                },
                "mm:manifest": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/manifest.TypedSchema"
                    }
                },
                "mm:publisher": {
                    "type": "string"
                },
                "mm:rightsHolder": {
                    "type": "string"
                }
            }
        },
        "manifest.TypedSchema": {
            "type": "object",
            "properties": {
                "@id": {
                    "type": "string"
                },
                "mm:schema": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "Metadata Manifest Index Server",
	Description: "Register and search metadata manifest objects",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
